//export pages branches
export { default as Homepage } from '../pages/Homepage';
export { default as About } from './about_pages/About';
export { default as Blog } from '../pages/Blog';
export { default as Mission } from './about_pages/OurMission';
export { default as ContactUs } from '../pages/ContactUs';
export { default as Cta } from '../pages/Cta';
export { default as Services } from './service_pages/Services';
export { default as Management } from './service_pages/Management';
export { default as Education } from './service_pages/Education';
export {default as Travel} from './service_pages/Travel';
export { default as CoachingAndTraining } from './service_pages/CoachingAndTraining';
export { default as Media } from './about_pages/Media';
export { default as Career } from '../pages/Career';
export { default as OurGovernance } from './about_pages/OurGovernance';
export { default as OurTeam } from './about_pages/OurTeam';
export { default as OurHistory } from '../pages/about_pages/OurHistory';
export {default as HowWeWork} from './about_pages/HowWeWork';
export { default as AgricultureIndustry } from './industry_pages/AgricultureIndustry';
export { default as AutomotiveIndustry } from './industry_pages/AutomotiveIndustry';
export { default as ConstructionIndustry } from './industry_pages/ConstructionIndustry';
export { default as EducationIndustry } from './industry_pages/EducationIndustry';
export { default as FinancialIndustry } from './industry_pages/FinancialIndustry';
export { default as HealthcareIndustry } from './industry_pages/HealthcareIndustry';
export { default as LifeSciencesIndustry } from './industry_pages/LifeSciencesIndustry';
export { default as PublicAndSocialIndustry } from './industry_pages/PublicAndSocialIndustry';
export { default as RealEstateIndustry } from './industry_pages/RealEstateIndustry';
export { default as RetailIndustry } from './industry_pages/RetailIndustry';
export { default as TechnologyIndustry } from './industry_pages/TechnologyIndustry';
export { default as TravelLogisticsIndustry } from './industry_pages/TravelLogisticsIndustry';
export { default as ArtificialIntelligence } from './insight_pages/ArtificialIntelligence';