//export pages branches
export { default as Homepage } from '../pages/Homepage';
export { default as About } from './about_pages/About';
export { default as Blog } from '../pages/Blog';
export { default as Mission } from './about_pages/OurMission';
export { default as ContactUs } from '../pages/ContactUs';
export { default as Cta } from '../pages/Cta';
export { default as Services } from './service_pages/Services';
export { default as Management } from './service_pages/Management';
export { default as Education } from './service_pages/Education';
export {default as Travel} from './service_pages/Travel';
export { default as CoachingAndTraining } from './service_pages/CoachingAndTraining';
export { default as Media } from './about_pages/Media';
export { default as Career } from '../pages/Career';
export { default as OurGovernance } from './about_pages/OurGovernance';
export { default as OurTeam } from './about_pages/OurTeam';
export { default as OurHistory } from '../pages/about_pages/OurHistory';
export {default as HowWeWork} from './about_pages/HowWeWork';
export { default as AgricultureIndustry } from './industry_pages/AgricultureIndustry';
/* export { default as AutomotiveIndustry } from '../pages/AutomotiveIndustry';
export { default as ConstructionIndustry } from '../pages/ConstructionIndustry';
export { default as EnergyIndustry } from '../pages/EnergyIndustry';
export { default as FinancialServicesIndustry } from '../pages/FinancialServicesIndustry';
export { default as HealthcareIndustry } from '../pages/HealthcareIndustry';
export { default as ManufacturingIndustry } from '../pages/ManufacturingIndustry';
export { default as RetailIndustry } from '../pages/RetailIndustry';
export { default as TechnologyIndustry } from '../pages/TechnologyIndustry';
export { default as TelecommunicationsIndustry } from '../pages/TelecommunicationsIndustry';
export { default as TransportationIndustry } from '../pages/TransportationIndustry'; */
export { default as ArtificialIntelligence } from './insight_pages/ArtificialIntelligence';